In [ ]:
alimport pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('train.csv')

In [ ]:
data.head()

Acceleration x (m/s^2)  Acceleration y (m/s^2)  Acceleration z (m/s^2)  \
0               -0.436000                   2.780                    10.1   
1                0.000299                   2.350                    11.2   
2                0.353000                   1.880                    12.0   
3                0.949000                   1.380                    11.9   
4                1.440000                   0.877                    11.3   

   Absolute acceleration (m/s^2)    gFx    gFy    gFz  gFTotal  \
0                           10.5 -0.162 -0.396 -0.734    0.849   
1                           11.5 -0.146 -0.390 -0.771    0.876   
2                           12.1 -0.120 -0.377 -0.809    0.901   
3                           12.0 -0.095 -0.359 -0.833    0.912   
4                           11.4 -0.080 -0.346 -0.838    0.911   

   Gyroscope x (rad/s)  Gyroscope y (rad/s)  Gyroscope z (rad/s)  \
0               -0.398                0.335               -0.436   
1               -0.118                0.944                0.268   
2                0.179                1.490                1.000   
3                0.536                2.130                1.760   
4                0.994                2.910                2.680   

   Absolute (rad/s) Activity  
0             0.678  running  
1             0.989  running  
2             1.810  running  
3             2.820  running  
4             4.080  running

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 730 entries, 0 to 729
Data columns (total 13 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Acceleration x (m/s^2)         730 non-null    float64
 1   Acceleration y (m/s^2)         730 non-null    float64
 2   Acceleration z (m/s^2)         730 non-null    float64
 3   Absolute acceleration (m/s^2)  730 non-null    float64
 4   gFx                            730 non-null    float64
 5   gFy                            730 non-null    float64
 6   gFz                            730 non-null    float64
 7   gFTotal                        730 non-null    float64
 8   Gyroscope x (rad/s)            730 non-null    float64
 9   Gyroscope y (rad/s)            730 non-null    float64
 10  Gyroscope z (rad/s)            730 non-null    float64
 11  Absolute (rad/s)               730 non-null    float64
 12  Activity                       730 non-null    obj

In [ ]:
print("Shape of the dataset:", data.shape)

Shape of the dataset: (730, 13)


In [ ]:
print("Columns:", data.columns.tolist())

Columns: ['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)', 'Absolute acceleration (m/s^2)', 'gFx', 'gFy', 'gFz', 'gFTotal', 'Gyroscope x (rad/s)', 'Gyroscope y (rad/s)', 'Gyroscope z (rad/s)', 'Absolute (rad/s)', 'Activity']


In [ ]:
print("Data types:\n", data.dtypes)

Data types:
 Acceleration x (m/s^2)           float64
Acceleration y (m/s^2)           float64
Acceleration z (m/s^2)           float64
Absolute acceleration (m/s^2)    float64
gFx                              float64
gFy                              float64
gFz                              float64
gFTotal                          float64
Gyroscope x (rad/s)              float64
Gyroscope y (rad/s)              float64
Gyroscope z (rad/s)              float64
Absolute (rad/s)                 float64
Activity                          object
dtype: object


In [ ]:
missing_values = data.isnull().sum()
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 Acceleration x (m/s^2)           0
Acceleration y (m/s^2)           0
Acceleration z (m/s^2)           0
Absolute acceleration (m/s^2)    0
gFx                              0
gFy                              0
gFz                              0
gFTotal                          0
Gyroscope x (rad/s)              0
Gyroscope y (rad/s)              0
Gyroscope z (rad/s)              0
Absolute (rad/s)                 0
Activity                         0
dtype: int64


In [ ]:
duplicates = data.duplicated().sum()
print("Number of duplicate rows:", duplicates)

Number of duplicate rows: 0


In [ ]:
print("Numeric columns summary:\n", data.describe())

Numeric columns summary:
        Acceleration x (m/s^2)  Acceleration y (m/s^2)  Acceleration z (m/s^2)  \
count              730.000000              730.000000              730.000000   
mean                 1.326619                3.813343                9.205425   
std                  4.708711                2.835812                7.131099   
min                 -0.996000               -0.924000               -0.704000   
25%                  0.146000                2.010000                6.110000   
50%                  0.301500                2.350000                9.430000   
75%                  1.127500                5.845000                9.670000   
max                 62.600000               17.800000               76.800000   

       Absolute acceleration (m/s^2)         gFx         gFy         gFz  \
count                     730.000000  730.000000  730.000000  730.000000   
mean                       11.014479    0.038910   -0.204593   -0.956705   
std             

In [ ]:
print("Non-numeric columns summary:\n", data.describe(include=['object']))

Non-numeric columns summary:
        Activity
count       730
unique        3
top     running
freq        255


## Numpy aggregate functions

In [ ]:
min_values = np.min(data[['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']].values, axis=0)
print("Minimum values for each axis:", min_values)

Minimum values for each axis: [-0.996 -0.924 -0.704]


In [ ]:
max_values = np.max(data[['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']].values, axis=0)
print("Maximum values for each axis:", max_values)

Maximum values for each axis: [62.6 17.8 76.8]


In [ ]:
sum_values = np.sum(data[['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']].values, axis=0)
print("Sum of values for each axis:", sum_values)

Sum of values for each axis: [ 968.432118 2783.7407   6719.9602  ]


In [ ]:
mean_values = np.mean(data[['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']].values, axis=0)
print("Mean values for each axis:", mean_values)

Mean values for each axis: [1.32661934 3.81334342 9.20542493]


In [ ]:
median_values = np.median(data[['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']].values, axis=0)
print("Median values for each axis:", median_values)

Median values for each axis: [0.3015 2.35   9.43  ]


In [ ]:
std_values = np.std(data[['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']].values, axis=0)
print("Standard Deviation values for each axis:", std_values)

Standard Deviation values for each axis: [4.70548459 2.83386929 7.12621255]


In [ ]:
variance_values = np.var(data[['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']].values, axis=0)
print("Variance values for each axis:", variance_values)

Variance values for each axis: [22.14158525  8.03081518 50.7829053 ]


In [ ]:
range_values = np.ptp(data[['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']].values, axis=0)
print("Range (Max - Min) for each axis:", range_values)

Range (Max - Min) for each axis: [63.596 18.724 77.504]


In [ ]:
cumulative_sum_limited = np.cumsum(data['Acceleration x (m/s^2)'].values[:10])
print("Cumulative sum for 10 values of Acceleration x (m/s^2):", cumulative_sum_limited)

Cumulative sum for 10 values of Acceleration x (m/s^2): [-0.436    -0.435701 -0.082701  0.866299  2.306299  3.956299  5.546299
  7.406299  9.466299 11.946299]


In [ ]:
cumulative_product_limited = np.cumprod(data['Acceleration x (m/s^2)'].values[:10])
print("Cumulative product 10 values of Acceleration x (m/s^2):", cumulative_product_limited)

Cumulative product 10 values of Acceleration x (m/s^2): [-4.36000000e-01 -1.30364000e-04 -4.60184920e-05 -4.36715489e-05
 -6.28870304e-05 -1.03763600e-04 -1.64984124e-04 -3.06870471e-04
 -6.32153171e-04 -1.56773986e-03]


In [ ]:
absolute_values_limited = np.abs(data['Acceleration x (m/s^2)'].values[:10])
print("Absolute values for 10 values of Acceleration x (m/s^2):", absolute_values_limited)

Absolute values for 10 values of Acceleration x (m/s^2): [4.36e-01 2.99e-04 3.53e-01 9.49e-01 1.44e+00 1.65e+00 1.59e+00 1.86e+00
 2.06e+00 2.48e+00]


In [ ]:
log_values_limited = np.log(np.abs(data['Acceleration x (m/s^2)'].values[:10]) + 1e-6)
print("Logarithm for 10 values of Acceleration x (m/s^2):", log_values_limited)

Logarithm for 10 values of Acceleration x (m/s^2): [-0.83011074 -8.11172808 -1.04128439 -0.05234543  0.36464381  0.50077589
  0.46373465  0.62057703  0.72270647  0.90825896]


In [ ]:
exp_values_limited = np.exp(data['Acceleration x (m/s^2)'].values[:10])
print("Exponential for 10 values of Acceleration x (m/s^2):", exp_values_limited)

Exponential for 10 values of Acceleration x (m/s^2): [ 0.64661773  1.00029904  1.42333114  2.58312524  4.22069582  5.20697983
  4.90374893  6.42373677  7.84596981 11.94126442]


In [ ]:
sqrt_values_limited = np.sqrt(np.abs(data['Acceleration x (m/s^2)'].values[:10]))
print("Square root for 10 values of Acceleration x (m/s^2):", sqrt_values_limited)

Square root for 10 values of Acceleration x (m/s^2): [0.66030296 0.01729162 0.59413803 0.97416631 1.2        1.28452326
 1.26095202 1.36381817 1.43527001 1.57480157]




---



# Indexing operations
### Access specific row

In [ ]:
first_row = data.iloc[0].values
print("First row:", first_row)

First row: [-0.436 2.78 10.1 10.5 -0.162 -0.396 -0.734 0.849 -0.398 0.335 -0.436
 0.678 'running']


### Access specific column

In [ ]:
acceleration_x_column = data['Acceleration x (m/s^2)'].values
print("First 10 values of Acceleration x (m/s^2):", acceleration_x_column[:10])

First 10 values of Acceleration x (m/s^2): [-4.36e-01  2.99e-04  3.53e-01  9.49e-01  1.44e+00  1.65e+00  1.59e+00
  1.86e+00  2.06e+00  2.48e+00]


### Access specific element

In [ ]:
specific_element = data.iloc[0]['Acceleration x (m/s^2)']
print("Element at row 0, column 'Acceleration x (m/s^2)':", specific_element)

Element at row 0, column 'Acceleration x (m/s^2)': -0.436


### Slicing rows

In [ ]:
first_five_rows = data.iloc[:5].values
print("First 5 rows:\n", first_five_rows)

First 5 rows:
 [[-0.436 2.78 10.1 10.5 -0.162 -0.396 -0.734 0.849 -0.398 0.335 -0.436
  0.678 'running']
 [0.000299 2.35 11.2 11.5 -0.146 -0.39 -0.771 0.876 -0.118 0.944 0.268
  0.989 'running']
 [0.353 1.88 12.0 12.1 -0.12 -0.377 -0.809 0.901 0.179 1.49 1.0 1.81
  'running']
 [0.949 1.38 11.9 12.0 -0.095 -0.359 -0.833 0.912 0.536 2.13 1.76 2.82
  'running']
 [1.44 0.877 11.3 11.4 -0.08 -0.346 -0.838 0.911 0.994 2.91 2.68 4.08
  'running']]


### Slicing columns

In [ ]:
selected_columns = data[['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)']].values
print("Selected columns:\n", selected_columns)

Selected columns:
 [[-4.36e-01  2.78e+00]
 [ 2.99e-04  2.35e+00]
 [ 3.53e-01  1.88e+00]
 ...
 [ 1.55e+00  6.48e+00]
 [ 9.36e-01  6.27e+00]
 [-4.51e-01  5.28e+00]]


### Conditional indexing

In [ ]:
positive_acceleration_x = data[data['Acceleration x (m/s^2)'] > 0].values
print("Rows where 'Acceleration x (m/s^2)' > 0:\n", positive_acceleration_x)

Rows where 'Acceleration x (m/s^2)' > 0:
 [[0.000299 2.35 11.2 ... 0.268 0.989 'running']
 [0.353 1.88 12.0 ... 1.0 1.81 'running']
 [0.949 1.38 11.9 ... 1.76 2.82 'running']
 ...
 [1.92 5.79 17.9 ... 1.65 2.05 'running']
 [1.55 6.48 14.6 ... -0.56 0.595 'running']
 [0.936 6.27 11.3 ... -0.711 0.739 'running']]


### Fancy indexing

In [ ]:
fancy_index = data.iloc[[0, 2, 4]][['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)']].values
print("Fancy indexing result:\n", fancy_index)

Fancy indexing result:
 [[-0.436  2.78 ]
 [ 0.353  1.88 ]
 [ 1.44   0.877]]


### Access Specific Range of Rows and Columns


In [ ]:
subset_data = data.iloc[1:6, 0:3].values
print("Subset of rows 1 to 5 and columns 0 to 2:\n", subset_data)

Subset of rows 1 to 5 and columns 0 to 2:
 [[2.99e-04 2.35e+00 1.12e+01]
 [3.53e-01 1.88e+00 1.20e+01]
 [9.49e-01 1.38e+00 1.19e+01]
 [1.44e+00 8.77e-01 1.13e+01]
 [1.65e+00 7.91e-01 1.05e+01]]




---



### Unique values

In [ ]:
for column in data.columns:
    unique_values = data[column].unique()
    print(f"Unique values in {column}:\n", unique_values[:10])
    print(f"Total unique values in {column}: {len(unique_values)}\n")

Unique values in Acceleration x (m/s^2):
 [-4.36e-01  2.99e-04  3.53e-01  9.49e-01  1.44e+00  1.65e+00  1.59e+00
  1.86e+00  2.06e+00  2.48e+00]
Total unique values in Acceleration x (m/s^2): 540

Unique values in Acceleration y (m/s^2):
 [ 2.78   2.35   1.88   1.38   0.877  0.791  0.848  0.166 -0.473 -0.763]
Total unique values in Acceleration y (m/s^2): 359

Unique values in Acceleration z (m/s^2):
 [10.1  11.2  12.   11.9  11.3  10.5   9.31  8.21  8.27  9.23]
Total unique values in Acceleration z (m/s^2): 381

Unique values in Absolute acceleration (m/s^2):
 [10.5  11.5  12.1  12.   11.4  10.7   9.49  8.42  8.54  9.59]
Total unique values in Absolute acceleration (m/s^2): 319

Unique values in gFx:
 [-0.162 -0.146 -0.12  -0.095 -0.08  -0.064 -0.063 -0.083 -0.128 -0.175]
Total unique values in gFx: 386

Unique values in gFy:
 [-0.396 -0.39  -0.377 -0.359 -0.346 -0.345 -0.349 -0.354 -0.365 -0.371]
Total unique values in gFy: 378

Unique values in gFz:
 [-0.734 -0.771 -0.809 -0.833 -0.

### Counting Activity Occurrences

In [ ]:
activity_counts = data['Activity'].value_counts()
print("Activity counts:\n", activity_counts)

Activity counts:
 Activity
running     255
standing    238
walking     237
Name: count, dtype: int64


### Outlier Detection in Numeric Columns

In [ ]:
numeric_columns = data.select_dtypes(include=[np.number]).columns
for col in numeric_columns:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[col] < lower_bound) | (data[col] > upper_bound)]
    print(f"Outliers in {col}: {len(outliers)}")

Outliers in Acceleration x (m/s^2): 67
Outliers in Acceleration y (m/s^2): 2
Outliers in Acceleration z (m/s^2): 73
Outliers in Absolute acceleration (m/s^2): 154
Outliers in gFx: 130
Outliers in gFy: 126
Outliers in gFz: 161
Outliers in gFTotal: 161
Outliers in Gyroscope x (rad/s): 120
Outliers in Gyroscope y (rad/s): 55
Outliers in Gyroscope z (rad/s): 112
Outliers in Absolute (rad/s): 50


### Numeric Summary Statistics

In [ ]:
numeric_summary = data[numeric_cols].agg(['mean', 'median', 'std', 'min', 'max'])
print("Numeric Summary Statistics:\n", numeric_summary)

Numeric Summary Statistics:
         Acceleration x (m/s^2)  Acceleration y (m/s^2)  \
mean                  1.326619                3.813343   
median                0.301500                2.350000   
std                   4.708711                2.835812   
min                  -0.996000               -0.924000   
max                  62.600000               17.800000   

        Acceleration z (m/s^2)  Absolute acceleration (m/s^2)       gFx  \
mean                  9.205425                      11.014479  0.038910   
median                9.430000                       9.750000  0.001000   
std                   7.131099                       7.794078  0.224131   
min                  -0.704000                       1.180000 -0.899000   
max                  76.800000                      99.200000  0.969000   

             gFy       gFz   gFTotal  Gyroscope x (rad/s)  \
mean   -0.204593 -0.956705  1.037944             0.309477   
median -0.198000 -0.974000  0.997500             

### Range of Numeric Columns

In [ ]:
ranges = data[numeric_cols].max() - data[numeric_cols].min()
print("Range of Numeric Columns:\n", ranges)

Range of Numeric Columns:
 Acceleration x (m/s^2)           63.59600
Acceleration y (m/s^2)           18.72400
Acceleration z (m/s^2)           77.50400
Absolute acceleration (m/s^2)    98.02000
gFx                               1.86800
gFy                               2.44300
gFz                               3.87200
gFTotal                           3.77600
Gyroscope x (rad/s)               7.11200
Gyroscope y (rad/s)               5.64600
Gyroscope z (rad/s)               6.62900
Absolute (rad/s)                  7.77685
dtype: float64


### Standard Deviation and Variance of Acceleration Columns

In [ ]:
acceleration_cols = ['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']
acceleration_std_dev = data[acceleration_cols].std()
acceleration_variance = data[acceleration_cols].var()

print("Standard Deviation of Acceleration Columns:\n", acceleration_std_dev)
print("Variance of Acceleration Columns:\n", acceleration_variance)

Standard Deviation of Acceleration Columns:
 Acceleration x (m/s^2)    4.708711
Acceleration y (m/s^2)    2.835812
Acceleration z (m/s^2)    7.131099
dtype: float64
Variance of Acceleration Columns:
 Acceleration x (m/s^2)    22.171958
Acceleration y (m/s^2)     8.041831
Acceleration z (m/s^2)    50.852566
dtype: float64


### Standard Deviation and Variance of Gforce columns

In [ ]:
gf_cols = ['gFx', 'gFy', 'gFz']
gf_std_dev = data[gf_cols].std()
gf_variance = data[gf_cols].var()

print("Standard Deviation of gF Columns:\n", gf_std_dev)
print("Variance of gF Columns:\n", gf_variance)

Standard Deviation of gF Columns:
 gFx    0.224131
gFy    0.219248
gFz    0.448569
dtype: float64
Variance of gF Columns:
 gFx    0.050235
gFy    0.048069
gFz    0.201214
dtype: float64


### Standard Deviation and Variance of gyroscope columns

In [ ]:
gyroscope_cols = ['Gyroscope x (rad/s)', 'Gyroscope y (rad/s)', 'Gyroscope z (rad/s)']
std_dev = data[gyroscope_cols].std()
variance = data[gyroscope_cols].var()

print("Standard Deviation of Gyroscope Columns:\n", std_dev)
print("Variance of Gyroscope Columns:\n", variance)

Standard Deviation of Gyroscope Columns:
 Gyroscope x (rad/s)    0.928435
Gyroscope y (rad/s)    0.871062
Gyroscope z (rad/s)    0.999058
dtype: float64
Variance of Gyroscope Columns:
 Gyroscope x (rad/s)    0.861992
Gyroscope y (rad/s)    0.758749
Gyroscope z (rad/s)    0.998117
dtype: float64


### Calculating Total Acceleration Magnitude

In [ ]:
data['Total Acceleration Magnitude'] = np.sqrt(
    data['Acceleration x (m/s^2)']**2 +
    data['Acceleration y (m/s^2)']**2 +
    data['Acceleration z (m/s^2)']**2
)
print("Added 'Total Acceleration Magnitude' column:\n", data[['Total Acceleration Magnitude']].head())

Added 'Total Acceleration Magnitude' column:
    Total Acceleration Magnitude
0                     10.484679
1                     11.443885
2                     12.151502
3                     12.017279
4                     11.425092


### Absolute Mean and Maximum of Accelerations

In [ ]:
acceleration_cols = ['Acceleration x (m/s^2)', 'Acceleration y (m/s^2)', 'Acceleration z (m/s^2)']
absolute_mean = data[acceleration_cols].abs().mean()
absolute_max = data[acceleration_cols].abs().max()

print("Absolute Mean of Accelerations:\n", absolute_mean)
print("Absolute Max of Accelerations:\n", absolute_max)

Absolute Mean of Accelerations:
 Acceleration x (m/s^2)    1.515018
Acceleration y (m/s^2)    3.823333
Acceleration z (m/s^2)    9.209882
dtype: float64
Absolute Max of Accelerations:
 Acceleration x (m/s^2)    62.6
Acceleration y (m/s^2)    17.8
Acceleration z (m/s^2)    76.8
dtype: float64


### Absolute Mean and Maximum of Gforce

In [ ]:
gf_cols = ['gFx', 'gFy', 'gFz']
gf_absolute_mean = data[gf_cols].abs().mean()
gf_absolute_max = data[gf_cols].abs().max()

print("Absolute Mean of gF Columns:\n", gf_absolute_mean)
print("Absolute Max of gF Columns:\n", gf_absolute_max)

Absolute Mean of gF Columns:
 gFx    0.134921
gFy    0.236336
gFz    0.957566
dtype: float64
Absolute Max of gF Columns:
 gFx    0.969
gFy    1.420
gFz    3.739
dtype: float64


### Absolute Mean and Maximum of gyroscope


In [ ]:
gyroscope_cols = ['Gyroscope x (rad/s)', 'Gyroscope y (rad/s)', 'Gyroscope z (rad/s)']
gyroscope_absolute_mean = data[gyroscope_cols].abs().mean()
gyroscope_absolute_max = data[gyroscope_cols].abs().max()

print("Absolute Mean of Gyroscope Columns:\n", gyroscope_absolute_mean)
print("Absolute Max of Gyroscope Columns:\n", gyroscope_absolute_max)

Absolute Mean of Gyroscope Columns:
 Gyroscope x (rad/s)    0.491579
Gyroscope y (rad/s)    0.553021
Gyroscope z (rad/s)    0.569885
dtype: float64
Absolute Max of Gyroscope Columns:
 Gyroscope x (rad/s)    6.21
Gyroscope y (rad/s)    4.71
Gyroscope z (rad/s)    5.63
dtype: float64


### Activity summary

In [ ]:
activity_summary = data.groupby('Activity')[numeric_cols].agg(['mean', 'median', 'std'])
print("Activity-wise Summary:\n", activity_summary)

Activity-wise Summary:
          Acceleration x (m/s^2)                   Acceleration y (m/s^2)  \
                           mean  median       std                   mean   
Activity                                                                   
running                3.395183  1.5900  7.509744               3.829595   
standing               0.266655  0.2595  0.073271               2.045924   
walking                0.165386 -0.0268  0.821628               5.570734   

                          Acceleration z (m/s^2)                    \
         median       std                   mean median        std   
Activity                                                             
running    2.94  2.905050              11.458609   8.44  11.156348   
standing   2.05  0.082818               9.561050   9.56   0.116963   
walking    6.27  3.082071               6.423987   7.41   3.119224   

         Absolute acceleration (m/s^2)  ... Gyroscope x (rad/s)  \
                               